### ISSUE TITLE
Implement camera in GUI

### ISSUE THREAD

**Issue by ABotelho23** [ABotelho23/aacdnProject#43]

**Comment by thekidd54** [comment]
GUI has features to send number of pictures to camera & video length 
-node needs to properly handle requests
Gallery has been implemented to view pictures/videos taken
-not 100% yet

**Comment by ABotelho23** [comment]
Currently picture number is definitely broken on client side. Expectation in the end will be just as you said, to send the number of pictures to take.

Maybe have a standard amount of time between each picture? Node will also have to send ACK before starting work, cause it'll just timeout in multi picture requests if not. I read something in the RFC about empty responses?

Can't recall how that works for video.

**Comment by ABotelho23** [comment]
We'll also have to verify the encoding on the videos taken aren't too demanding or large.
